"""Added shared_with_user_id to Share model

Revision ID: 2f52945b5ab5
Revises: b2adec27af24
Create Date: 2025-05-03 13:08:15.962348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f52945b5ab5'
down_revision = 'b2adec27af24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_share_shared_with_user_id',  # Add a meaningful name for the constraint
            'user',
            ['shared_with_user_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shared_with_user_id')

    # ### end Alembic commands ###
