"""Removed distance from workout table

Revision ID: b2adec27af24
Revises: f16ba9cad399
Create Date: 2025-04-30 22:44:06.180288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2adec27af24'
down_revision = 'f16ba9cad399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('distance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
