"""Added description of activity to workout table

Revision ID: f16ba9cad399
Revises: a7e998af757d
Create Date: 2025-04-30 22:27:19.850685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16ba9cad399'
down_revision = 'a7e998af757d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=False, server_default='Light jogging'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
